name = "garden-local"
main = "src/index.ts"
compatibility_date = "2022-10-04"
node_compat=true

[vars]
GARDEN_TYPE="moss"

[env.dev]
NODE_ENV="development"

[env.local]
NODE_ENV="local"

[env.staging]
NODE_ENV="staging"

[env.production]
NODE_ENV="production"